// apps/admin-starter-vue/src/pages/SettingsPage.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useAuthStore } from '@/stores/auth.store';
import { useTheme } from '@/providers/useTheme';
import { Button, Input, Label, Card, CardHeader, CardTitle, CardContent, Tabs, TabsList, TabsTrigger, TabsContent, Switch, Separator, Avatar, toast } from '@ncripta/forge-vue';

const auth = useAuthStore();
const { theme, setTheme } = useTheme();
const darkMode = ref(theme.value === 'dark');

const handleToggle = (checked: boolean) => {
  darkMode.value = checked;
  setTheme(checked ? 'dark' : 'light');
};

const handleSave = () => {
  toast.success('Perfil actualizado correctamente');
};
</script>

<template>
  <div class="max-w-7xl mx-auto space-y-6">
    <div>
      <h1 class="text-2xl sm:text-3xl font-bold text-surface-900 tracking-tight">Configuración</h1>
      <p class="text-sm text-surface-500 mt-1">Administra tu cuenta y preferencias.</p>
    </div>

    <Tabs default-value="profile">
      <TabsList>
        <TabsTrigger value="profile">Perfil</TabsTrigger>
        <TabsTrigger value="security">Seguridad</TabsTrigger>
        <TabsTrigger value="preferences">Preferencias</TabsTrigger>
      </TabsList>

      <TabsContent value="profile">
        <Card class="mt-4">
          <CardHeader><CardTitle>Información personal</CardTitle></CardHeader>
          <CardContent>
            <form class="space-y-4" @submit.prevent="handleSave">
              <div class="flex items-center gap-4">
                <Avatar size="xl" :fallback="auth.user?.name?.charAt(0) || 'U'" />
                <Button intent="secondary" type="button">Cambiar avatar</Button>
              </div>
              <Separator />
              <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <div class="space-y-2">
                  <Label>Nombre</Label>
                  <Input :model-value="auth.user?.name" />
                </div>
                <div class="space-y-2">
                  <Label>Email</Label>
                  <Input type="email" :model-value="auth.user?.email" />
                </div>
              </div>
              <Button type="submit" intent="primary">Guardar cambios</Button>
            </form>
          </CardContent>
        </Card>
      </TabsContent>

      <TabsContent value="security">
        <Card class="mt-4">
          <CardHeader><CardTitle>Cambiar contraseña</CardTitle></CardHeader>
          <CardContent>
            <form class="space-y-4 max-w-md" @submit.prevent="toast.success('Contraseña actualizada')">
              <div class="space-y-2"><Label>Contraseña actual</Label><Input type="password" /></div>
              <div class="space-y-2"><Label>Nueva contraseña</Label><Input type="password" /></div>
              <div class="space-y-2"><Label>Confirmar contraseña</Label><Input type="password" /></div>
              <Button type="submit" intent="primary">Actualizar contraseña</Button>
            </form>
          </CardContent>
        </Card>
      </TabsContent>

      <TabsContent value="preferences">
        <Card class="mt-4">
          <CardHeader><CardTitle>Preferencias de interfaz</CardTitle></CardHeader>
          <CardContent class="space-y-6">
            <div class="flex items-center justify-between">
              <div>
                <p class="text-sm font-medium text-text-main">Modo oscuro</p>
                <p class="text-xs text-text-muted">Activa el tema oscuro</p>
              </div>
              <Switch :checked="darkMode" @update:checked="handleToggle" />
            </div>
          </CardContent>
        </Card>
      </TabsContent>
    </Tabs>
  </div>
</template>

// apps/admin-starter/src/pages/settings/SettingsPage.tsx
import { useState } from 'react';
import { useAuthStore } from '@/stores/auth.store';
import { useTheme } from '@/providers/ThemeProvider';
import {
  Button, Input, Label, Card, CardHeader, CardTitle, CardContent,
  Tabs, TabsList, TabsTrigger, TabsContent,
  Avatar, Switch, Separator, toast,
} from '@ncripta/forge-react';

export function SettingsPage() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold text-text-main">Configuración</h1>
        <p className="text-text-muted mt-1">Administra tu cuenta y preferencias.</p>
      </div>

      <Tabs defaultValue="profile">
        <TabsList>
          <TabsTrigger value="profile">Perfil</TabsTrigger>
          <TabsTrigger value="security">Seguridad</TabsTrigger>
          <TabsTrigger value="preferences">Preferencias</TabsTrigger>
        </TabsList>

        <TabsContent value="profile"><ProfileTab /></TabsContent>
        <TabsContent value="security"><SecurityTab /></TabsContent>
        <TabsContent value="preferences"><PreferencesTab /></TabsContent>
      </Tabs>
    </div>
  );
}

function ProfileTab() {
  const { user } = useAuthStore();

  const handleSave = (e: React.FormEvent) => {
    e.preventDefault();
    toast.success('Perfil actualizado correctamente');
  };

  return (
    <Card className="mt-4">
      <CardHeader><CardTitle>Información personal</CardTitle></CardHeader>
      <CardContent>
        <form onSubmit={handleSave} className="space-y-4">
          <div className="flex items-center gap-4">
            <Avatar size="xl" fallback={user?.name?.charAt(0) || 'U'} />
            <Button intent="secondary" type="button">Cambiar avatar</Button>
          </div>
          <Separator />
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <div className="space-y-2">
              <Label>Nombre</Label>
              <Input defaultValue={user?.name} />
            </div>
            <div className="space-y-2">
              <Label>Email</Label>
              <Input type="email" defaultValue={user?.email} />
            </div>
          </div>
          <Button type="submit">Guardar cambios</Button>
        </form>
      </CardContent>
    </Card>
  );
}

function SecurityTab() {
  const handleSave = (e: React.FormEvent) => {
    e.preventDefault();
    toast.success('Contraseña actualizada');
  };

  return (
    <Card className="mt-4">
      <CardHeader><CardTitle>Cambiar contraseña</CardTitle></CardHeader>
      <CardContent>
        <form onSubmit={handleSave} className="space-y-4 max-w-md">
          <div className="space-y-2">
            <Label>Contraseña actual</Label>
            <Input type="password" />
          </div>
          <div className="space-y-2">
            <Label>Nueva contraseña</Label>
            <Input type="password" />
          </div>
          <div className="space-y-2">
            <Label>Confirmar nueva contraseña</Label>
            <Input type="password" />
          </div>
          <Button type="submit">Actualizar contraseña</Button>
        </form>
      </CardContent>
    </Card>
  );
}

function PreferencesTab() {
  const { theme, setTheme } = useTheme();
  const [darkMode, setDarkMode] = useState(theme === 'dark');

  const handleToggle = (checked: boolean) => {
    setDarkMode(checked);
    setTheme(checked ? 'dark' : 'light');
  };

  return (
    <Card className="mt-4">
      <CardHeader><CardTitle>Preferencias de interfaz</CardTitle></CardHeader>
      <CardContent className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <p className="text-sm font-medium text-text-main">Modo oscuro</p>
            <p className="text-xs text-text-muted">Activa el tema oscuro de la interfaz</p>
          </div>
          <Switch checked={darkMode} onCheckedChange={handleToggle} />
        </div>
        <Separator />
        <div className="flex items-center justify-between">
          <div>
            <p className="text-sm font-medium text-text-main">Notificaciones</p>
            <p className="text-xs text-text-muted">Recibir notificaciones push</p>
          </div>
          <Switch checked={true} onCheckedChange={() => toast.info('Funcionalidad simulada')} />
        </div>
      </CardContent>
    </Card>
  );
}
