// packages/react/src/components/Combobox/Combobox.tsx
import * as React from 'react';
import { Command as CommandPrimitive } from 'cmdk';
import * as PopoverPrimitive from '@radix-ui/react-popover';
import { cn } from '../../utils/cn';

export interface ComboboxOption {
  value: string;
  label: string;
  disabled?: boolean;
}

export interface ComboboxProps {
  options: ComboboxOption[];
  value?: string;
  onValueChange?: (value: string) => void;
  placeholder?: string;
  searchPlaceholder?: string;
  emptyMessage?: string;
  className?: string;
  disabled?: boolean;
}

const Combobox: React.FC<ComboboxProps> = ({
  options,
  value,
  onValueChange,
  placeholder = 'Seleccionar...',
  searchPlaceholder = 'Buscar...',
  emptyMessage = 'Sin resultados.',
  className,
  disabled = false,
}) => {
  const [open, setOpen] = React.useState(false);
  const selectedLabel = options.find((opt) => opt.value === value)?.label;

  return (
    <PopoverPrimitive.Root open={open} onOpenChange={setOpen}>
      <PopoverPrimitive.Trigger
        disabled={disabled}
        className={cn(
          'flex h-10 w-full items-center justify-between rounded-md border border-surface-border bg-surface-background px-3 py-2 text-sm ring-offset-surface-background focus:outline-none focus:ring-2 focus:ring-primary-main focus:ring-offset-1 disabled:cursor-not-allowed disabled:opacity-50',
          !selectedLabel && 'text-text-muted',
          className
        )}
      >
        <span className="truncate">{selectedLabel || placeholder}</span>
        <svg className="h-4 w-4 shrink-0 text-text-muted" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M8 9l4-4 4 4m0 6l-4 4-4-4" />
        </svg>
      </PopoverPrimitive.Trigger>
      <PopoverPrimitive.Portal>
        <PopoverPrimitive.Content
          className="z-50 w-[var(--radix-popover-trigger-width)] rounded-md border border-surface-border bg-surface-raised shadow-md outline-none animate-in fade-in-0 zoom-in-95"
          sideOffset={4}
          align="start"
        >
          <CommandPrimitive className="flex flex-col">
            <div className="flex items-center border-b border-surface-border px-3">
              <svg className="mr-2 h-4 w-4 shrink-0 text-text-muted" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
              <CommandPrimitive.Input
                placeholder={searchPlaceholder}
                className="flex h-9 w-full bg-transparent py-3 text-sm text-text-main outline-none placeholder:text-text-muted"
              />
            </div>
            <CommandPrimitive.List className="max-h-[200px] overflow-y-auto p-1">
              <CommandPrimitive.Empty className="py-4 text-center text-sm text-text-muted">
                {emptyMessage}
              </CommandPrimitive.Empty>
              {options.map((option) => (
                <CommandPrimitive.Item
                  key={option.value}
                  value={option.label}
                  disabled={option.disabled}
                  onSelect={() => {
                    onValueChange?.(option.value === value ? '' : option.value);
                    setOpen(false);
                  }}
                  className="relative flex cursor-pointer select-none items-center rounded-sm px-2 py-1.5 text-sm text-text-main outline-none aria-selected:bg-primary-subtle aria-selected:text-primary-main data-[disabled]:pointer-events-none data-[disabled]:opacity-50"
                >
                  <svg
                    className={cn('mr-2 h-4 w-4', value === option.value ? 'opacity-100' : 'opacity-0')}
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth={2}
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                  </svg>
                  {option.label}
                </CommandPrimitive.Item>
              ))}
            </CommandPrimitive.List>
          </CommandPrimitive>
        </PopoverPrimitive.Content>
      </PopoverPrimitive.Portal>
    </PopoverPrimitive.Root>
  );
};
Combobox.displayName = 'Combobox';

export { Combobox };

// packages/vue/src/components/Combobox/Combobox.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { ComboboxRoot, ComboboxInput, ComboboxContent, ComboboxItem, ComboboxEmpty, ComboboxAnchor } from 'radix-vue';
import { cn } from '../../utils/cn';

export interface ComboboxOption {
  value: string;
  label: string;
  disabled?: boolean;
}

interface Props {
  options: ComboboxOption[];
  modelValue?: string;
  placeholder?: string;
  searchPlaceholder?: string;
  emptyMessage?: string;
  class?: string;
}

const props = withDefaults(defineProps<Props>(), {
  placeholder: 'Seleccionar...',
  searchPlaceholder: 'Buscar...',
  emptyMessage: 'Sin resultados.',
});

const emit = defineEmits<{ 'update:modelValue': [value: string] }>();
const searchTerm = ref('');

const filtered = computed(() =>
  props.options.filter((o) => o.label.toLowerCase().includes(searchTerm.value.toLowerCase()))
);
</script>

<template>
  <ComboboxRoot :model-value="modelValue" @update:model-value="emit('update:modelValue', $event as string)" :display-value="(val) => options.find(o => o.value === val)?.label || ''">
    <ComboboxAnchor :class="cn('flex h-10 w-full items-center rounded-md border border-surface-border bg-surface-background px-3 py-2 text-sm', props.class)">
      <ComboboxInput :placeholder="placeholder" class="flex-1 bg-transparent outline-none placeholder:text-text-muted text-text-main" @input="searchTerm = ($event.target as HTMLInputElement).value" />
    </ComboboxAnchor>
    <ComboboxContent class="z-50 mt-1 max-h-[200px] overflow-y-auto rounded-md border border-surface-border bg-surface-raised p-1 shadow-md">
      <ComboboxEmpty class="py-4 text-center text-sm text-text-muted">{{ emptyMessage }}</ComboboxEmpty>
      <ComboboxItem
        v-for="option in filtered"
        :key="option.value"
        :value="option.value"
        :disabled="option.disabled"
        class="relative flex cursor-pointer select-none items-center rounded-sm px-2 py-1.5 text-sm text-text-main outline-none data-[highlighted]:bg-primary-subtle data-[highlighted]:text-primary-main data-[disabled]:pointer-events-none data-[disabled]:opacity-50"
      >
        {{ option.label }}
      </ComboboxItem>
    </ComboboxContent>
  </ComboboxRoot>
</template>
