// packages/react/src/components/DataTable/DataTable.tsx
import * as React from 'react';
import {
  type ColumnDef,
  type SortingState,
  type RowSelectionState,
  type PaginationState,
  flexRender,
  getCoreRowModel,
  getSortedRowModel,
  getPaginationRowModel,
  useReactTable,
} from '@tanstack/react-table';
import { cn } from '../../utils/cn';

// --- Table primitives ---

const Table = React.forwardRef<HTMLTableElement, React.HTMLAttributes<HTMLTableElement>>(
  ({ className, ...props }, ref) => (
    <div className="relative w-full overflow-auto">
      <table ref={ref} className={cn('w-full caption-bottom text-sm', className)} {...props} />
    </div>
  )
);
Table.displayName = 'Table';

const TableHeader = React.forwardRef<HTMLTableSectionElement, React.HTMLAttributes<HTMLTableSectionElement>>(
  ({ className, ...props }, ref) => (
    <thead ref={ref} className={cn('[&_tr]:border-b', className)} {...props} />
  )
);
TableHeader.displayName = 'TableHeader';

const TableBody = React.forwardRef<HTMLTableSectionElement, React.HTMLAttributes<HTMLTableSectionElement>>(
  ({ className, ...props }, ref) => (
    <tbody ref={ref} className={cn('[&_tr:last-child]:border-0', className)} {...props} />
  )
);
TableBody.displayName = 'TableBody';

const TableRow = React.forwardRef<HTMLTableRowElement, React.HTMLAttributes<HTMLTableRowElement>>(
  ({ className, ...props }, ref) => (
    <tr
      ref={ref}
      className={cn(
        'border-b border-surface-border transition-colors hover:bg-surface-sunken data-[state=selected]:bg-primary-subtle',
        className
      )}
      {...props}
    />
  )
);
TableRow.displayName = 'TableRow';

const TableHead = React.forwardRef<HTMLTableCellElement, React.ThHTMLAttributes<HTMLTableCellElement>>(
  ({ className, ...props }, ref) => (
    <th
      ref={ref}
      className={cn(
        'h-10 px-4 text-left align-middle font-medium text-text-muted [&:has([role=checkbox])]:pr-0',
        className
      )}
      {...props}
    />
  )
);
TableHead.displayName = 'TableHead';

const TableCell = React.forwardRef<HTMLTableCellElement, React.TdHTMLAttributes<HTMLTableCellElement>>(
  ({ className, ...props }, ref) => (
    <td
      ref={ref}
      className={cn('p-4 align-middle text-text-main [&:has([role=checkbox])]:pr-0', className)}
      {...props}
    />
  )
);
TableCell.displayName = 'TableCell';

// --- DataTable component ---

export interface DataTableProps<TData, TValue> {
  columns: ColumnDef<TData, TValue>[];
  data: TData[];
  pageSize?: number;
  enableSelection?: boolean;
  onRowSelectionChange?: (selection: RowSelectionState) => void;
  className?: string;
}

function DataTable<TData, TValue>({
  columns,
  data,
  pageSize = 10,
  enableSelection = false,
  onRowSelectionChange,
  className,
}: DataTableProps<TData, TValue>) {
  const [sorting, setSorting] = React.useState<SortingState>([]);
  const [rowSelection, setRowSelection] = React.useState<RowSelectionState>({});
  const [pagination, setPagination] = React.useState<PaginationState>({
    pageIndex: 0,
    pageSize,
  });

  React.useEffect(() => {
    onRowSelectionChange?.(rowSelection);
  }, [rowSelection, onRowSelectionChange]);

  const table = useReactTable({
    data,
    columns,
    state: { sorting, rowSelection, pagination },
    onSortingChange: setSorting,
    onRowSelectionChange: setRowSelection,
    onPaginationChange: setPagination,
    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    enableRowSelection: enableSelection,
  });

  return (
    <div className={cn('space-y-4', className)}>
      <div className="rounded-lg border border-surface-border overflow-hidden">
        <Table>
          <TableHeader>
            {table.getHeaderGroups().map((headerGroup) => (
              <TableRow key={headerGroup.id}>
                {headerGroup.headers.map((header) => (
                  <TableHead
                    key={header.id}
                    className={header.column.getCanSort() ? 'cursor-pointer select-none' : ''}
                    onClick={header.column.getToggleSortingHandler()}
                  >
                    <div className="flex items-center gap-1">
                      {header.isPlaceholder
                        ? null
                        : flexRender(header.column.columnDef.header, header.getContext())}
                      {header.column.getIsSorted() === 'asc' && <span>↑</span>}
                      {header.column.getIsSorted() === 'desc' && <span>↓</span>}
                    </div>
                  </TableHead>
                ))}
              </TableRow>
            ))}
          </TableHeader>
          <TableBody>
            {table.getRowModel().rows.length ? (
              table.getRowModel().rows.map((row) => (
                <TableRow key={row.id} data-state={row.getIsSelected() ? 'selected' : undefined}>
                  {row.getVisibleCells().map((cell) => (
                    <TableCell key={cell.id}>
                      {flexRender(cell.column.columnDef.cell, cell.getContext())}
                    </TableCell>
                  ))}
                </TableRow>
              ))
            ) : (
              <TableRow>
                <TableCell colSpan={columns.length} className="h-24 text-center text-text-muted">
                  Sin resultados.
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </div>

      {/* Pagination */}
      <div className="flex items-center justify-between px-2">
        {enableSelection && (
          <p className="text-sm text-text-muted">
            {table.getFilteredSelectedRowModel().rows.length} de{' '}
            {table.getFilteredRowModel().rows.length} fila(s) seleccionada(s).
          </p>
        )}
        <div className="flex items-center gap-2 ml-auto">
          <button
            className="inline-flex items-center justify-center h-8 px-3 text-xs font-medium rounded-md border border-surface-border bg-surface-background text-text-main hover:bg-surface-sunken disabled:opacity-50 disabled:pointer-events-none transition-colors duration-fast"
            onClick={() => table.previousPage()}
            disabled={!table.getCanPreviousPage()}
          >
            Anterior
          </button>
          <span className="text-sm text-text-secondary">
            {table.getState().pagination.pageIndex + 1} / {table.getPageCount()}
          </span>
          <button
            className="inline-flex items-center justify-center h-8 px-3 text-xs font-medium rounded-md border border-surface-border bg-surface-background text-text-main hover:bg-surface-sunken disabled:opacity-50 disabled:pointer-events-none transition-colors duration-fast"
            onClick={() => table.nextPage()}
            disabled={!table.getCanNextPage()}
          >
            Siguiente
          </button>
        </div>
      </div>
    </div>
  );
}

export {
  DataTable,
  Table,
  TableHeader,
  TableBody,
  TableRow,
  TableHead,
  TableCell,
};

// packages/vue/src/components/DataTable/DataTable.vue
<script setup lang="ts" generic="TData">
import { ref, computed, watch } from 'vue';
import {
  useVueTable,
  getCoreRowModel,
  getSortedRowModel,
  getPaginationRowModel,
  FlexRender,
  type ColumnDef,
  type SortingState,
  type RowSelectionState,
} from '@tanstack/vue-table';
import { cn } from '../../utils/cn';

export interface DataTableProps<TData = any> {
  columns: ColumnDef<TData, any>[];
  data: TData[];
  pageSize?: number;
  enableSelection?: boolean;
  class?: string;
}

const props = withDefaults(defineProps<DataTableProps>(), {
  pageSize: 10,
  enableSelection: false,
});

const emit = defineEmits<{ 'selection-change': [selection: RowSelectionState] }>();

const sorting = ref<SortingState>([]);
const rowSelection = ref<RowSelectionState>({});

watch(rowSelection, (val) => emit('selection-change', val), { deep: true });

const table = useVueTable({
  get data() { return props.data; },
  get columns() { return props.columns; },
  state: {
    get sorting() { return sorting.value; },
    get rowSelection() { return rowSelection.value; },
  },
  onSortingChange: (updater) => {
    sorting.value = typeof updater === 'function' ? updater(sorting.value) : updater;
  },
  onRowSelectionChange: (updater) => {
    rowSelection.value = typeof updater === 'function' ? updater(rowSelection.value) : updater;
  },
  getCoreRowModel: getCoreRowModel(),
  getSortedRowModel: getSortedRowModel(),
  getPaginationRowModel: getPaginationRowModel(),
  enableRowSelection: props.enableSelection,
  initialState: {
    pagination: { pageSize: props.pageSize },
  },
});

const pageIndex = computed(() => table.getState().pagination.pageIndex);
const pageCount = computed(() => table.getPageCount());
</script>

<template>
  <div :class="cn('space-y-4', props.class)">
    <div class="rounded-lg border border-surface-border overflow-hidden">
      <div class="relative w-full overflow-auto">
        <table class="w-full caption-bottom text-sm">
          <thead class="[&_tr]:border-b">
            <tr v-for="headerGroup in table.getHeaderGroups()" :key="headerGroup.id" class="border-b border-surface-border">
              <th
                v-for="header in headerGroup.headers"
                :key="header.id"
                :class="cn('h-10 px-4 text-left align-middle font-medium text-text-muted', header.column.getCanSort() && 'cursor-pointer select-none')"
                @click="header.column.getToggleSortingHandler()?.($event)"
              >
                <div class="flex items-center gap-1">
                  <FlexRender v-if="!header.isPlaceholder" :render="header.column.columnDef.header" :props="header.getContext()" />
                  <span v-if="header.column.getIsSorted() === 'asc'">↑</span>
                  <span v-if="header.column.getIsSorted() === 'desc'">↓</span>
                </div>
              </th>
            </tr>
          </thead>
          <tbody class="[&_tr:last-child]:border-0">
            <template v-if="table.getRowModel().rows.length">
              <tr
                v-for="row in table.getRowModel().rows"
                :key="row.id"
                :data-state="row.getIsSelected() ? 'selected' : undefined"
                class="border-b border-surface-border transition-colors hover:bg-surface-sunken data-[state=selected]:bg-primary-subtle"
              >
                <td v-for="cell in row.getVisibleCells()" :key="cell.id" class="p-4 align-middle text-text-main">
                  <FlexRender :render="cell.column.columnDef.cell" :props="cell.getContext()" />
                </td>
              </tr>
            </template>
            <template v-else>
              <tr>
                <td :colspan="props.columns.length" class="h-24 text-center text-text-muted">
                  Sin resultados.
                </td>
              </tr>
            </template>
          </tbody>
        </table>
      </div>
    </div>

    <!-- Pagination -->
    <div class="flex items-center justify-between px-2">
      <p v-if="enableSelection" class="text-sm text-text-muted">
        {{ table.getFilteredSelectedRowModel().rows.length }} de {{ table.getFilteredRowModel().rows.length }} fila(s) seleccionada(s).
      </p>
      <div class="flex items-center gap-2 ml-auto">
        <button
          class="inline-flex items-center justify-center h-8 px-3 text-xs font-medium rounded-md border border-surface-border bg-surface-background text-text-main hover:bg-surface-sunken disabled:opacity-50 disabled:pointer-events-none transition-colors"
          :disabled="!table.getCanPreviousPage()"
          @click="table.previousPage()"
        >
          Anterior
        </button>
        <span class="text-sm text-text-secondary">{{ pageIndex + 1 }} / {{ pageCount }}</span>
        <button
          class="inline-flex items-center justify-center h-8 px-3 text-xs font-medium rounded-md border border-surface-border bg-surface-background text-text-main hover:bg-surface-sunken disabled:opacity-50 disabled:pointer-events-none transition-colors"
          :disabled="!table.getCanNextPage()"
          @click="table.nextPage()"
        >
          Siguiente
        </button>
      </div>
    </div>
  </div>
</template>
