// apps/admin-starter-vue/src/pages/ProjectsPage.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useQuery, useMutation, useQueryClient } from '@tanstack/vue-query';
import { ProjectService, type ProjectRecord } from '@/services/project.service';
import { Card, CardContent, Icon, Badge, Button, Progress, Dialog, DialogContent, DialogTrigger, DialogTitle, DialogDescription, DialogClose, Input, Label, Textarea, Spinner, toast } from '@forge-ui/vue';

const queryClient = useQueryClient();
const dialogOpen = ref(false);

const { data, isLoading } = useQuery({
  queryKey: ['projects'],
  queryFn: () => ProjectService.getAll(),
});

const createMutation = useMutation({
  mutationFn: (payload: Pick<ProjectRecord, 'name' | 'description' | 'icon' | 'iconBg'>) => ProjectService.create(payload),
  onSuccess: (project) => {
    queryClient.invalidateQueries({ queryKey: ['projects'] });
    toast.success(`Proyecto "${project.name}" creado`);
    dialogOpen.value = false;
  },
});

const deleteMutation = useMutation({
  mutationFn: (id: string) => ProjectService.delete(id),
  onSuccess: () => {
    queryClient.invalidateQueries({ queryKey: ['projects'] });
    toast.success('Proyecto eliminado');
  },
});

const handleCreate = (e: Event) => {
  const form = new FormData(e.target as HTMLFormElement);
  createMutation.mutate({
    name: form.get('name') as string,
    description: form.get('description') as string,
    icon: 'Globe',
    iconBg: 'bg-sky-50 text-sky-600',
  });
};

const statusConfig: Record<string, { label: string; intent: 'success' | 'warning' | 'default' }> = {
  active: { label: 'En progreso', intent: 'success' },
  review: { label: 'Revisión', intent: 'warning' },
  completed: { label: 'Completado', intent: 'default' },
  archived: { label: 'Archivado', intent: 'default' },
};

const openCreate = () => { dialogOpen.value = true; };
</script>

<template>
  <div class="max-w-7xl mx-auto space-y-6">
    <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
      <div>
        <h1 class="text-2xl sm:text-3xl font-bold text-surface-900 tracking-tight">Proyectos</h1>
        <p class="text-sm text-surface-500 mt-1">Gestiona y monitorea tus espacios de trabajo.</p>
      </div>
      <Dialog v-model:open="dialogOpen">
        <DialogTrigger as-child>
          <Button intent="primary"><Icon name="Plus" :size="16" /> Nuevo Proyecto</Button>
        </DialogTrigger>
        <DialogContent>
          <DialogTitle>Crear nuevo proyecto</DialogTitle>
          <DialogDescription>Completa la información para iniciar un espacio de trabajo.</DialogDescription>
          <form class="space-y-4 mt-4" @submit.prevent="handleCreate">
            <div class="space-y-2">
              <Label required>Nombre</Label>
              <Input name="name" placeholder="Ej: Landing Page v2" required />
            </div>
            <div class="space-y-2">
              <Label>Descripción</Label>
              <Textarea name="description" placeholder="Describe el objetivo del proyecto..." />
            </div>
            <div class="flex gap-2 pt-4 justify-end">
              <DialogClose as-child>
                <Button type="button" intent="secondary">Cancelar</Button>
              </DialogClose>
              <Button type="submit" intent="primary" :loading="createMutation.isPending.value">Crear</Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>
    </div>

    <!-- Loading -->
    <div v-if="isLoading" class="flex items-center justify-center py-16">
      <Spinner size="lg" />
    </div>

    <!-- Grid -->
    <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <Card v-for="project in data?.data" :key="project.id" class="p-5 hover:shadow-md transition-shadow group flex flex-col h-full">
        <CardContent class="p-0 flex flex-col h-full">
          <div class="flex justify-between items-start mb-4">
            <div :class="`w-12 h-12 rounded-lg flex items-center justify-center ${project.iconBg}`">
              <Icon :name="project.icon" :size="24" />
            </div>
            <Button intent="ghost" size="sm" class="opacity-0 group-hover:opacity-100 transition-opacity" @click="deleteMutation.mutate(project.id)">
              <Icon name="Trash2" :size="14" class="text-danger-main" />
            </Button>
          </div>
          <div class="mb-4 flex-1">
            <div class="flex items-center gap-2 mb-1">
              <h3 class="text-lg font-bold text-surface-900">{{ project.name }}</h3>
              <Badge :intent="statusConfig[project.status]?.intent || 'default'" variant="outline">
                {{ statusConfig[project.status]?.label || project.status }}
              </Badge>
            </div>
            <p class="text-sm text-surface-500 line-clamp-2">{{ project.description }}</p>
          </div>
          <div class="mb-4">
            <div class="flex justify-between text-xs font-medium mb-1.5">
              <span class="text-surface-500">Progreso</span>
              <span class="text-surface-900">{{ project.progress }}%</span>
            </div>
            <Progress :value="project.progress" :color="project.progressColor" />
          </div>
        </CardContent>
      </Card>

      <!-- Add new card -->
      <button
        class="border-2 border-dashed border-surface-200 rounded-lg p-5 hover:border-primary-400 hover:bg-primary-50 transition-colors group flex flex-col items-center justify-center min-h-[200px]"
        @click="openCreate"
      >
        <div class="w-14 h-14 rounded-full bg-surface-100 text-surface-400 group-hover:bg-primary-100 group-hover:text-primary-600 flex items-center justify-center mb-4 transition-colors">
          <Icon name="Plus" :size="24" />
        </div>
        <h3 class="text-lg font-bold text-surface-900 group-hover:text-primary-700">Crear Nuevo</h3>
      </button>
    </div>
  </div>
</template>

// apps/admin-starter/src/pages/projects/ProjectsPage.tsx
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { ProjectService, type ProjectRecord, type ProjectFilters } from '@/services/project.service';
import {
  Button, Badge, Icon, Input, Card, CardContent,
  Tabs, TabsList, TabsTrigger,
  AvatarGroup, Progress, Label, Textarea, Spinner,
  Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter, DialogClose,
  Select, SelectTrigger, SelectValue, SelectContent, SelectItem,
  DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator,
  toast,
  type IconName,
} from '@forge-ui/react';

const statusConfig = {
  active: { label: 'En progreso', intent: 'success' as const },
  review: { label: 'Revisión', intent: 'warning' as const },
  completed: { label: 'Completado', intent: 'default' as const },
  archived: { label: 'Archivado', intent: 'default' as const },
};

const ICON_OPTIONS: { value: string; label: string; bg: string }[] = [
  { value: 'ShoppingCart', label: 'E-commerce', bg: 'bg-blue-50 text-blue-600' },
  { value: 'Bot', label: 'IA / Agentes', bg: 'bg-purple-50 text-purple-600' },
  { value: 'BarChart2', label: 'Analítica', bg: 'bg-rose-50 text-rose-600' },
  { value: 'Globe', label: 'Web', bg: 'bg-sky-50 text-sky-600' },
  { value: 'Smartphone', label: 'Mobile', bg: 'bg-amber-50 text-amber-600' },
  { value: 'Server', label: 'Backend', bg: 'bg-emerald-50 text-emerald-600' },
];

// --- Project Card ---

function ProjectCard({ project, onDelete }: { project: ProjectRecord; onDelete: (id: string) => void }) {
  const status = statusConfig[project.status];

  return (
    <Card className="p-5 hover:shadow-md transition-shadow group flex flex-col h-full">
      <CardContent className="p-0 flex flex-col h-full">
        <div className="flex justify-between items-start mb-4">
          <div className={`w-12 h-12 rounded-lg flex items-center justify-center ${project.iconBg}`}>
            <Icon name={project.icon as IconName} size={24} />
          </div>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button intent="ghost" size="icon" className="opacity-0 group-hover:opacity-100 transition-opacity h-8 w-8">
                <Icon name="Ellipsis" size={18} />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuItem>Editar</DropdownMenuItem>
              <DropdownMenuItem>Duplicar</DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem onClick={() => onDelete(project.id)} className="text-danger-main">
                Eliminar
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>

        <div className="mb-4 flex-1">
          <div className="flex items-center gap-2 mb-1">
            <h3 className="text-lg font-bold text-surface-900 group-hover:text-primary-600 transition-colors cursor-pointer">
              {project.name}
            </h3>
            <Badge intent={status.intent} variant="outline">{status.label}</Badge>
          </div>
          <p className="text-sm text-surface-500 line-clamp-2">{project.description}</p>
        </div>

        <div className="mb-4">
          <div className="flex justify-between text-xs font-medium mb-1.5">
            <span className="text-surface-500">Progreso de tareas</span>
            <span className="text-surface-900">{project.progress}%</span>
          </div>
          <Progress value={project.progress} color={project.progressColor} />
        </div>

        <div className="flex items-center justify-between border-t border-surface-200 pt-4 mt-auto">
          <AvatarGroup avatars={project.members} max={3} size="sm" />
          <span className="text-xs text-surface-400 flex items-center gap-1">
            <Icon name={project.status === 'completed' ? 'CircleCheck' : 'Clock'} size={12} />
            {project.updatedAt}
          </span>
        </div>
      </CardContent>
    </Card>
  );
}

// --- New Project Dialog ---

function NewProjectDialog() {
  const queryClient = useQueryClient();
  const [open, setOpen] = useState(false);
  const [iconIdx, setIconIdx] = useState('0');

  const createMutation = useMutation({
    mutationFn: (data: Pick<ProjectRecord, 'name' | 'description' | 'icon' | 'iconBg'>) =>
      ProjectService.create(data),
    onSuccess: (project) => {
      queryClient.invalidateQueries({ queryKey: ['projects'] });
      toast.success(`Proyecto "${project.name}" creado correctamente`);
      setOpen(false);
    },
  });

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const form = new FormData(e.currentTarget);
    const selectedIcon = ICON_OPTIONS[Number(iconIdx)]!;

    createMutation.mutate({
      name: form.get('name') as string,
      description: form.get('description') as string,
      icon: selectedIcon.value,
      iconBg: selectedIcon.bg,
    });
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button intent="primary">
          <Icon name="Plus" size={16} />
          Nuevo Proyecto
        </Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Crear nuevo proyecto</DialogTitle>
          <DialogDescription>Completa la información para iniciar un nuevo espacio de trabajo.</DialogDescription>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4 mt-4">
          <div className="space-y-2">
            <Label htmlFor="name" required>Nombre del proyecto</Label>
            <Input id="name" name="name" placeholder="Ej: Landing Page v2" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="description">Descripción</Label>
            <Textarea id="description" name="description" placeholder="Describe brevemente el objetivo del proyecto..." />
          </div>
          <div className="space-y-2">
            <Label>Categoría</Label>
            <Select value={iconIdx} onValueChange={setIconIdx}>
              <SelectTrigger>
                <SelectValue placeholder="Seleccionar categoría" />
              </SelectTrigger>
              <SelectContent>
                {ICON_OPTIONS.map((opt, i) => (
                  <SelectItem key={opt.value} value={String(i)}>{opt.label}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <DialogFooter className="pt-4">
            <DialogClose asChild>
              <Button type="button" intent="secondary">Cancelar</Button>
            </DialogClose>
            <Button type="submit" intent="primary" loading={createMutation.isPending}>Crear proyecto</Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

// --- New Project Card ---

function NewProjectCard({ onClick }: { onClick: () => void }) {
  return (
    <button
      onClick={onClick}
      className="border-2 border-dashed border-surface-200 rounded-lg p-5 hover:border-primary-400 hover:bg-primary-50 transition-colors group flex flex-col items-center justify-center h-full min-h-[260px]"
    >
      <div className="w-14 h-14 rounded-full bg-surface-100 text-surface-400 group-hover:bg-primary-100 group-hover:text-primary-600 flex items-center justify-center mb-4 transition-colors">
        <Icon name="Plus" size={24} />
      </div>
      <h3 className="text-lg font-bold text-surface-900 group-hover:text-primary-700">Crear Nuevo</h3>
      <p className="text-sm text-surface-500 mt-1 text-center max-w-[200px]">
        Inicia un nuevo espacio de trabajo desde cero o usa una plantilla.
      </p>
    </button>
  );
}

// --- Page ---

export function ProjectsPage() {
  const queryClient = useQueryClient();
  const [search, setSearch] = useState('');
  const [tab, setTab] = useState('all');

  const filters: ProjectFilters = {
    ...(search && { search }),
    ...(tab !== 'all' && { status: tab === 'active' ? 'active' : tab }),
  };

  const { data, isLoading } = useQuery({
    queryKey: ['projects', filters],
    queryFn: () => ProjectService.getAll(filters),
  });

  const deleteMutation = useMutation({
    mutationFn: ProjectService.delete,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['projects'] });
      toast.success('Proyecto eliminado');
    },
  });

  return (
    <div className="max-w-7xl mx-auto space-y-6">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl font-bold text-surface-900 tracking-tight">Proyectos</h1>
          <p className="text-sm text-surface-500 mt-1">Gestiona y monitorea tus espacios de trabajo activos.</p>
        </div>
        <div className="flex items-center gap-3">
          <Button intent="secondary">
            <Icon name="Filter" size={16} />
            Filtros
          </Button>
          <NewProjectDialog />
        </div>
      </div>

      {/* Tabs & Search */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <Tabs value={tab} onValueChange={setTab}>
          <TabsList>
            <TabsTrigger value="all">Todos</TabsTrigger>
            <TabsTrigger value="active">Activos</TabsTrigger>
            <TabsTrigger value="completed">Completados</TabsTrigger>
            <TabsTrigger value="archived">Archivados</TabsTrigger>
          </TabsList>
        </Tabs>
        <div className="w-full sm:w-64">
          <Input
            placeholder="Buscar..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
      </div>

      {/* Projects Grid */}
      {isLoading ? (
        <div className="flex items-center justify-center py-16">
          <Spinner size="lg" />
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {data?.data.map((project) => (
            <ProjectCard key={project.id} project={project} onDelete={(id) => deleteMutation.mutate(id)} />
          ))}
          <NewProjectCard onClick={() => {}} />
        </div>
      )}
    </div>
  );
}
