// packages/react/src/components/Input/Input.tsx
import * as React from 'react';
import { type VariantProps } from 'class-variance-authority';
import { inputVariants } from '@ncripta/forge-variants';
import { cn } from '../../utils/cn';

export interface InputProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'size'>,
    VariantProps<typeof inputVariants> {}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, size, error, type, ...props }, ref) => {
    return (
      <input
        type={type}
        className={cn(inputVariants({ size, error, className }))}
        ref={ref}
        {...props}
      />
    );
  }
);
Input.displayName = 'Input';

export { Input, inputVariants };

// packages/vue/src/components/Input/Input.vue
<script setup lang="ts">
import { computed } from 'vue';
import { type VariantProps } from 'class-variance-authority';
import { inputVariants } from '@ncripta/forge-variants';
import { cn } from '../../utils/cn';

type InputVariantProps = VariantProps<typeof inputVariants>;

interface Props {
  size?: InputVariantProps['size'];
  error?: boolean;
  modelValue?: string;
  class?: string;
}

const props = withDefaults(defineProps<Props>(), {
  size: 'md',
  error: false,
});

const emit = defineEmits<{
  'update:modelValue': [value: string];
}>();

const classes = computed(() =>
  cn(inputVariants({ size: props.size, error: props.error }), props.class)
);

const handleInput = (e: Event) => {
  emit('update:modelValue', (e.target as HTMLInputElement).value);
};
</script>

<template>
  <input :class="classes" :value="modelValue" @input="handleInput" v-bind="$attrs" />
</template>
