// packages/vue/src/components/Alert/Alert.vue
<script setup lang="ts">
import { computed } from 'vue';
import { type VariantProps } from 'class-variance-authority';
import { alertVariants } from '@ncripta/forge-variants';
import { cn } from '../../utils/cn';

type AlertVariantProps = VariantProps<typeof alertVariants>;

interface Props {
  intent?: AlertVariantProps['intent'];
  class?: string;
}

const props = withDefaults(defineProps<Props>(), {
  intent: 'default',
});

const classes = computed(() => cn(alertVariants({ intent: props.intent }), props.class));
</script>

<template>
  <div role="alert" :class="classes" v-bind="$attrs">
    <slot />
  </div>
</template>

// packages/react/src/components/Alert/Alert.tsx
import * as React from 'react';
import { type VariantProps } from 'class-variance-authority';
import { alertVariants } from '@ncripta/forge-variants';
import { cn } from '../../utils/cn';

export interface AlertProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof alertVariants> {}

const Alert = React.forwardRef<HTMLDivElement, AlertProps>(
  ({ className, intent, ...props }, ref) => (
    <div
      ref={ref}
      role="alert"
      className={cn(alertVariants({ intent }), className)}
      {...props}
    />
  )
);
Alert.displayName = 'Alert';

const AlertTitle = React.forwardRef<HTMLHeadingElement, React.HTMLAttributes<HTMLHeadingElement>>(
  ({ className, ...props }, ref) => (
    <h5
      ref={ref}
      className={cn('mb-1 font-medium leading-none tracking-tight', className)}
      {...props}
    />
  )
);
AlertTitle.displayName = 'AlertTitle';

const AlertDescription = React.forwardRef<HTMLParagraphElement, React.HTMLAttributes<HTMLParagraphElement>>(
  ({ className, ...props }, ref) => (
    <p
      ref={ref}
      className={cn('text-sm [&_p]:leading-relaxed opacity-90', className)}
      {...props}
    />
  )
);
AlertDescription.displayName = 'AlertDescription';

export { Alert, AlertTitle, AlertDescription, alertVariants };
