// packages/react/src/components/Slider/Slider.tsx
import * as React from 'react';
import * as SliderPrimitive from '@radix-ui/react-slider';
import { cn } from '../../utils/cn';

export interface SliderProps extends React.ComponentPropsWithoutRef<typeof SliderPrimitive.Root> {}

const Slider = React.forwardRef<React.ElementRef<typeof SliderPrimitive.Root>, SliderProps>(
  ({ className, ...props }, ref) => (
    <SliderPrimitive.Root
      ref={ref}
      className={cn('relative flex w-full touch-none select-none items-center', className)}
      {...props}
    >
      <SliderPrimitive.Track className="relative h-2 w-full grow overflow-hidden rounded-full bg-surface-sunken">
        <SliderPrimitive.Range className="absolute h-full bg-primary-main" />
      </SliderPrimitive.Track>
      {(props.defaultValue || props.value || [0]).map((_, i) => (
        <SliderPrimitive.Thumb
          key={i}
          className="block h-5 w-5 rounded-full border-2 border-primary-main bg-surface-background ring-offset-surface-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-main focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50"
        />
      ))}
    </SliderPrimitive.Root>
  )
);
Slider.displayName = 'Slider';

export { Slider };

// packages/vue/src/components/Slider/Slider.vue
<script setup lang="ts">
import { SliderRoot, SliderTrack, SliderRange, SliderThumb } from 'radix-vue';
import { cn } from '../../utils/cn';

interface Props {
  modelValue?: number[];
  min?: number;
  max?: number;
  step?: number;
  class?: string;
}

const props = withDefaults(defineProps<Props>(), { min: 0, max: 100, step: 1 });
const emit = defineEmits<{ 'update:modelValue': [value: number[]] }>();

const handleUpdate = (val: number[] | undefined) => {
  if (val) emit('update:modelValue', val);
};
</script>

<template>
  <SliderRoot
    :model-value="modelValue || [0]"
    :min="min"
    :max="max"
    :step="step"
    @update:model-value="handleUpdate"
    :class="cn('relative flex w-full touch-none select-none items-center', props.class)"
    v-bind="$attrs"
  >
    <SliderTrack class="relative h-2 w-full grow overflow-hidden rounded-full bg-surface-sunken">
      <SliderRange class="absolute h-full bg-primary-main" />
    </SliderTrack>
    <SliderThumb class="block h-5 w-5 rounded-full border-2 border-primary-main bg-surface-background ring-offset-surface-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-main focus-visible:ring-offset-2" />
  </SliderRoot>
</template>
