// packages/react/src/components/Spinner/Spinner.tsx
import * as React from 'react';
import { type VariantProps } from 'class-variance-authority';
import { spinnerVariants } from '@ncripta/forge-variants';
import { cn } from '../../utils/cn';

export interface SpinnerProps
  extends React.SVGAttributes<SVGSVGElement>,
    VariantProps<typeof spinnerVariants> {}

const Spinner = React.forwardRef<SVGSVGElement, SpinnerProps>(
  ({ className, size, ...props }, ref) => (
    <svg
      ref={ref}
      className={cn(spinnerVariants({ size, className }))}
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      {...props}
    >
      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
    </svg>
  )
);
Spinner.displayName = 'Spinner';

export { Spinner, spinnerVariants };

// packages/vue/src/components/Spinner/Spinner.vue
<script setup lang="ts">
import { computed } from 'vue';
import { type VariantProps } from 'class-variance-authority';
import { spinnerVariants } from '@ncripta/forge-variants';
import { cn } from '../../utils/cn';

type SpinnerVariantProps = VariantProps<typeof spinnerVariants>;

interface Props {
  size?: SpinnerVariantProps['size'];
  class?: string;
}

const props = withDefaults(defineProps<Props>(), {
  size: 'md',
});

const classes = computed(() => cn(spinnerVariants({ size: props.size }), props.class));
</script>

<template>
  <svg :class="classes" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" v-bind="$attrs">
    <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" />
    <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
  </svg>
</template>
