// packages/vue/src/components/Label/Label.vue
<script setup lang="ts">
import { cn } from '../../utils/cn';

interface Props {
  required?: boolean;
  class?: string;
}

const props = withDefaults(defineProps<Props>(), {
  required: false,
});
</script>

<template>
  <label :class="cn('text-sm font-medium text-text-main leading-none', props.class)" v-bind="$attrs">
    <slot />
    <span v-if="required" class="text-danger-main ml-1">*</span>
  </label>
</template>

// packages/react/src/components/Label/Label.tsx
import * as React from 'react';
import { cn } from '../../utils/cn';

export interface LabelProps extends React.LabelHTMLAttributes<HTMLLabelElement> {
  required?: boolean;
}

const Label = React.forwardRef<HTMLLabelElement, LabelProps>(
  ({ className, required, children, ...props }, ref) => (
    <label
      ref={ref}
      className={cn(
        'text-sm font-medium text-text-main leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
        className
      )}
      {...props}
    >
      {children}
      {required && <span className="text-danger-main ml-1">*</span>}
    </label>
  )
);
Label.displayName = 'Label';

export { Label };
