// apps/admin-starter/src/pages/users/UsersPage.tsx
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { UserService, type UserRecord, type UserFilters } from '@/services/user.service';
import {
  Button, Input, Badge, Avatar,
  DataTable, type ColumnDef,
  Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription,
  DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator,
  Select, SelectTrigger, SelectValue, SelectContent, SelectItem,
  Label, toast,
} from '@forge-ui/react';

const columns: ColumnDef<UserRecord, unknown>[] = [
  {
    accessorKey: 'name',
    header: 'Usuario',
    cell: ({ row }) => (
      <div className="flex items-center gap-3">
        <Avatar size="sm" fallback={row.original.name.charAt(0)} />
        <div>
          <p className="font-medium text-text-main">{row.original.name}</p>
          <p className="text-xs text-text-muted">{row.original.email}</p>
        </div>
      </div>
    ),
  },
  {
    accessorKey: 'role',
    header: 'Rol',
    cell: ({ row }) => <Badge intent="primary" variant="subtle">{row.original.role}</Badge>,
  },
  {
    accessorKey: 'status',
    header: 'Estado',
    cell: ({ row }) => (
      <Badge intent={row.original.status === 'ACTIVE' ? 'success' : 'default'}>
        {row.original.status === 'ACTIVE' ? 'Activo' : 'Inactivo'}
      </Badge>
    ),
  },
  { accessorKey: 'createdAt', header: 'Creado' },
];

export function UsersPage() {
  const queryClient = useQueryClient();
  const [filters, setFilters] = useState<UserFilters>({ page: 1 });
  const [search, setSearch] = useState('');
  const [editUser, setEditUser] = useState<UserRecord | null>(null);
  const [sheetOpen, setSheetOpen] = useState(false);

  const { data, isLoading } = useQuery({
    queryKey: ['users', filters],
    queryFn: () => UserService.getAll(filters),
  });

  const deleteMutation = useMutation({
    mutationFn: UserService.delete,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['users'] });
      toast.success('Usuario eliminado correctamente');
    },
  });

  const handleSearch = () => {
    setFilters((f) => ({ ...f, page: 1, search }));
  };

  const handleEdit = (user: UserRecord) => {
    setEditUser(user);
    setSheetOpen(true);
  };

  // Add actions column
  const columnsWithActions: ColumnDef<UserRecord, unknown>[] = [
    ...columns,
    {
      id: 'actions',
      header: '',
      cell: ({ row }) => (
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button intent="ghost" size="icon">
              <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 6.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 12.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 18.75a.75.75 0 110-1.5.75.75 0 010 1.5z" />
              </svg>
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuItem onClick={() => handleEdit(row.original)}>Editar</DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem className="text-danger-main" onClick={() => deleteMutation.mutate(row.original.id)}>
              Eliminar
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      ),
    },
  ];

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-text-main">Usuarios</h1>
          <p className="text-text-muted mt-1">{data?.total || 0} usuarios registrados</p>
        </div>
        <Button onClick={() => { setEditUser(null); setSheetOpen(true); }}>+ Nuevo usuario</Button>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap items-center gap-3">
        <div className="flex items-center gap-2 flex-1 max-w-sm">
          <Input placeholder="Buscar por nombre o email..." value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && handleSearch()} />
          <Button intent="secondary" onClick={handleSearch}>Buscar</Button>
        </div>
        <Select onValueChange={(v) => setFilters((f) => ({ ...f, page: 1, role: v || undefined }))}>
          <SelectTrigger className="w-[140px]"><SelectValue placeholder="Rol" /></SelectTrigger>
          <SelectContent>
            <SelectItem value="SUPER_ADMIN">Super Admin</SelectItem>
            <SelectItem value="ADMIN">Admin</SelectItem>
            <SelectItem value="USER">User</SelectItem>
          </SelectContent>
        </Select>
        <Select onValueChange={(v) => setFilters((f) => ({ ...f, page: 1, status: v || undefined }))}>
          <SelectTrigger className="w-[140px]"><SelectValue placeholder="Estado" /></SelectTrigger>
          <SelectContent>
            <SelectItem value="ACTIVE">Activo</SelectItem>
            <SelectItem value="INACTIVE">Inactivo</SelectItem>
          </SelectContent>
        </Select>
      </div>

      {/* Table */}
      {isLoading ? (
        <div className="flex items-center justify-center py-12 text-text-muted">Cargando...</div>
      ) : (
        <DataTable columns={columnsWithActions} data={data?.data || []} enableSelection />
      )}

      {/* Edit Sheet */}
      <Sheet open={sheetOpen} onOpenChange={setSheetOpen}>
        <SheetContent>
          <SheetHeader>
            <SheetTitle>{editUser ? 'Editar usuario' : 'Nuevo usuario'}</SheetTitle>
            <SheetDescription>
              {editUser ? 'Modifica los datos del usuario.' : 'Completa los campos para crear un usuario.'}
            </SheetDescription>
          </SheetHeader>
          <UserForm user={editUser} onClose={() => setSheetOpen(false)} />
        </SheetContent>
      </Sheet>
    </div>
  );
}

// --- User Form inside Sheet ---
function UserForm({ user, onClose }: { user: UserRecord | null; onClose: () => void }) {
  const queryClient = useQueryClient();
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLoading(true);
    const form = new FormData(e.currentTarget);
    const payload = {
      name: form.get('name') as string,
      email: form.get('email') as string,
      role: (form.get('role') as UserRecord['role']) || 'USER',
      status: (form.get('status') as UserRecord['status']) || 'ACTIVE',
    };

    if (user) {
      await UserService.update(user.id, payload);
      toast.success('Usuario actualizado');
    } else {
      await UserService.create(payload);
      toast.success('Usuario creado');
    }

    setLoading(false);
    queryClient.invalidateQueries({ queryKey: ['users'] });
    onClose();
  };

  return (
    <form onSubmit={handleSubmit} className="mt-6 space-y-4">
      <div className="space-y-2">
        <Label htmlFor="name">Nombre</Label>
        <Input id="name" name="name" defaultValue={user?.name} required />
      </div>
      <div className="space-y-2">
        <Label htmlFor="email">Email</Label>
        <Input id="email" name="email" type="email" defaultValue={user?.email} required />
      </div>
      <div className="space-y-2">
        <Label htmlFor="role">Rol</Label>
        <select name="role" defaultValue={user?.role || 'USER'} className="flex h-10 w-full rounded-md border border-surface-border bg-surface-background px-3 py-2 text-sm">
          <option value="USER">User</option>
          <option value="ADMIN">Admin</option>
          <option value="SUPER_ADMIN">Super Admin</option>
        </select>
      </div>
      <div className="flex gap-2 pt-4">
        <Button type="submit" loading={loading} className="flex-1">{user ? 'Guardar' : 'Crear'}</Button>
        <Button type="button" intent="secondary" onClick={onClose}>Cancelar</Button>
      </div>
    </form>
  );
}

// apps/admin-starter-vue/src/pages/UsersPage.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useQuery, useMutation, useQueryClient } from '@tanstack/vue-query';
import { UserService, type UserRecord } from '@/services/user.service';
import { Button, Input, Label, Badge, Avatar, Icon, Spinner, Dialog, DialogContent, DialogTrigger, DialogTitle, DialogDescription, DialogClose, toast } from '@forge-ui/vue';

const queryClient = useQueryClient();
const search = ref('');
const filters = ref<Record<string, string | number>>({ page: 1 });
const dialogOpen = ref(false);

const { data, isLoading } = useQuery({
  queryKey: ['users', filters],
  queryFn: () => UserService.getAll(filters.value),
});

const createMutation = useMutation({
  mutationFn: (payload: Partial<UserRecord>) => UserService.create(payload),
  onSuccess: () => {
    queryClient.invalidateQueries({ queryKey: ['users'] });
    toast.success('Usuario creado correctamente');
    dialogOpen.value = false;
  },
});

const deleteMutation = useMutation({
  mutationFn: (id: string) => UserService.delete(id),
  onSuccess: () => {
    queryClient.invalidateQueries({ queryKey: ['users'] });
    toast.success('Usuario eliminado');
  },
});

const handleSearch = () => {
  filters.value = { ...filters.value, page: 1, search: search.value };
};

const handleCreate = (e: Event) => {
  const form = new FormData(e.target as HTMLFormElement);
  createMutation.mutate({
    name: form.get('name') as string,
    email: form.get('email') as string,
    role: (form.get('role') as UserRecord['role']) || 'USER',
    status: 'ACTIVE',
  });
};
</script>

<template>
  <div class="max-w-7xl mx-auto space-y-6">
    <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
      <div>
        <h1 class="text-2xl sm:text-3xl font-bold text-surface-900 tracking-tight">Usuarios</h1>
        <p class="text-sm text-surface-500 mt-1">{{ data?.total || 0 }} usuarios registrados</p>
      </div>
      <Dialog v-model:open="dialogOpen">
        <DialogTrigger as-child>
          <Button intent="primary"><Icon name="Plus" :size="16" /> Nuevo usuario</Button>
        </DialogTrigger>
        <DialogContent>
          <DialogTitle>Crear nuevo usuario</DialogTitle>
          <DialogDescription>Completa los campos para registrar un usuario.</DialogDescription>
          <form class="space-y-4 mt-4" @submit.prevent="handleCreate">
            <div class="space-y-2">
              <Label required>Nombre</Label>
              <Input name="name" placeholder="Nombre completo" required />
            </div>
            <div class="space-y-2">
              <Label required>Email</Label>
              <Input name="email" type="email" placeholder="usuario@ejemplo.com" required />
            </div>
            <div class="space-y-2">
              <Label>Rol</Label>
              <select name="role" class="flex h-10 w-full rounded-md border border-surface-border bg-surface-background px-3 py-2 text-sm text-text-main">
                <option value="USER">User</option>
                <option value="ADMIN">Admin</option>
                <option value="SUPER_ADMIN">Super Admin</option>
              </select>
            </div>
            <div class="flex gap-2 pt-4 justify-end">
              <DialogClose as-child>
                <Button type="button" intent="secondary">Cancelar</Button>
              </DialogClose>
              <Button type="submit" intent="primary" :loading="createMutation.isPending.value">Crear</Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>
    </div>

    <!-- Search -->
    <div class="flex items-center gap-2 max-w-sm">
      <Input placeholder="Buscar..." v-model="search" @keydown.enter="handleSearch" />
      <Button intent="secondary" @click="handleSearch">Buscar</Button>
    </div>

    <!-- Table -->
    <div v-if="isLoading" class="flex items-center justify-center py-16">
      <Spinner size="lg" />
    </div>
    <div v-else class="rounded-lg border border-surface-border overflow-hidden">
      <table class="w-full text-sm">
        <thead class="border-b border-surface-border">
          <tr>
            <th class="h-10 px-4 text-left font-medium text-text-muted">Usuario</th>
            <th class="h-10 px-4 text-left font-medium text-text-muted">Rol</th>
            <th class="h-10 px-4 text-left font-medium text-text-muted">Estado</th>
            <th class="h-10 px-4 text-left font-medium text-text-muted">Creado</th>
            <th class="h-10 px-4 text-left font-medium text-text-muted"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="user in data?.data" :key="user.id" class="border-b border-surface-border hover:bg-surface-sunken">
            <td class="p-4">
              <div class="flex items-center gap-3">
                <Avatar size="sm" :fallback="user.name.charAt(0)" />
                <div>
                  <p class="font-medium text-text-main">{{ user.name }}</p>
                  <p class="text-xs text-text-muted">{{ user.email }}</p>
                </div>
              </div>
            </td>
            <td class="p-4"><Badge intent="primary" variant="subtle">{{ user.role }}</Badge></td>
            <td class="p-4"><Badge :intent="user.status === 'ACTIVE' ? 'success' : 'default'">{{ user.status === 'ACTIVE' ? 'Activo' : 'Inactivo' }}</Badge></td>
            <td class="p-4 text-text-muted">{{ user.createdAt }}</td>
            <td class="p-4">
              <Button intent="ghost" size="sm" @click="deleteMutation.mutate(user.id)">
                <Icon name="Trash2" :size="14" class="text-danger-main" />
              </Button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>
